repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: local
    hooks:
      - id: go-code-checker
        name: Format Go Code
        entry: ./githooks/go.sh
        language: golang
        pass_filenames: false
      - id: go-test-runner
        name: Test Go Code
        entry: go test -v ./...
        language: golang
        pass_filenames: false
      - id: go-build
        name: Build Go Code
        entry: go build -o tracker.out cmd/tracker/tracker.go
        language: golang
        pass_filenames: false
