repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: local
    hooks:
      - id: go-linter
        name: Lint Go Code
        entry: make lint
        language: golang
        pass_filenames: false
      - id: go-test-runner
        name: Test Go Code
        entry: make test
        language: golang
        pass_filenames: false
